version: '3.9'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:covoiturage  # Ou MySQL si besoin
    depends_on:
      - frontend  # Optionnel

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Nginx sert Angular sur port 80 pour accès direct
    depends_on:
      - backend

  # Optionnel : DB MySQL
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_DATABASE: covoiturage_db
  #     MYSQL_ROOT_PASSWORD: root